version: "3"
services:
  notebook:
    build:
      context: .
      dockerfile: Dockerfile.notebook
    ports:
      - "8888:8888"
    restart: always
    environment:
      - GRANT_SUDO=yes
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ./work:/home/jovyan/work
    command: start-notebook.sh --NotebookApp.token=''
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres:13.0-alpine
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: analysis
      POSTGRES_INITDB_ARGS: “--encoding=UTF-8 --locale=ja_JP.UTF-8"
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    stdin_open: true
    tty: true
    entrypoint: "/bin/sh -c"
    command: '"tail -f /dev/null"'

volumes:
  db-data:
    driver: local
  work:
    driver: local