version: "3.8"
services:
  jupyterlab:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        GITHUB_USER: $GITHUB_USER
        GITHUB_EMAIL: $GITHUB_EMAIL
    container_name: "jupyterlab"
    environment:
      - DISPLAY=${HOST_NAME}:0
    ports:
      - 8888:8888
    restart: always
    volumes:
      - ./work:/work
      - ~/.Xauthority:/root/.Xauthority
    secrets:
      - user_ssh_key

secrets:
  user_ssh_key:
    file: $SSH_KEY_PATH