version: "3"
services:
  notebook:
    build:
      context: .
      dockerfile: Dockerfile.notebook
    ports:
      - "1234:8888"
    restart: always
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ./work:/home/jovyan/work
    command: start-notebook.sh --NotebookApp.token=''